# This workflow deploys the app on push or pull request

name: updateData

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push
  schedule:
  - cron: "0 0 * * *"

jobs:
  deploy:
    name: Update datasets
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install packages
        run: |
          Rscript installing_packages.R
      - name: Update datasets and deploy (if needed)
        run: |
          Rscript data-raw/updating_data.R ${{secrets.SHINYAPPS_TOKEN}} ${{secrets.SHINYAPPS_SECRET}}
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add . || echo "No changes to commit"
          git commit -m 'updating data' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
